const helmetByTeamId: Record<string, string> = {
  'east-peoria-red-raiders': '/images/helmets/east_peoria.png',
  'cathedral-golden-gales': '/images/helmets/Cathedral.png',
  'west-catholic-burrs': '/images/helmets/westcatholic.png',
  'deckerville-eagles': '/images/helmets/deckerville.png',
  'creston-polar-bears': '/images/helmets/creston.png',
  'excelsior-springs-tigers': '/images/helmets/excelsior.png',
  'turkeyfoot-rams': '/images/helmets/turkeyfoot.png',
  'illini-west-chargers': '/images/helmets/illini.png',
  'springfield-stars': '/images/helmets/springfieldstars.png',
  'leto-falcons-f5': '/images/helmets/leto.png',
  'east-grand-rapids-pioneers': '/images/helmets/eastgrandrapids.png',
  'oak-ridge': '/images/helmets/oakridge.png',
  'hinsdale-pacers': '/images/helmets/hinsdalepacers.png',
  'great-falls-bison': '/images/helmets/greatfallsbison.png',
  'lees-summit-tigers-f6': '/images/helmets/leesummit.png',
  'vincennes-lincoln-alices': '/images/helmets/Vincennes.png',
  'storm-lake-tornadoes': '/images/helmets/stormlake.png',
  'kimball-knights': '/images/helmets/kimballknights.png',
  'roosevelt-rough-riders': '/images/helmets/roosevelt.png',
  'hennessey-eagles': '/images/helmets/hennessey.png',
  'highland-park-giants': '/images/helmets/highlandpark.png',
  'simi-valley-pioneers': '/images/helmets/simivalley.png',
  'brophy-broncos': '/images/helmets/brophy.png',
  'cedaredge-bruins': '/images/helmets/cedaredge.png',
  'blacklick-vikings': '/images/helmets/blacklick.png',
  'lamar-trojans': '/images/helmets/lamar.png',
  'oak-grove-panthers': '/images/helmets/OAKGROVE.png',
  'paisley-panthers': '/images/helmets/paisleypanthers.png',
  'lake-shore-shorians': '/images/helmets/lakeshore.png',
  'ridge-bolts': '/images/helmets/Ridge.png',
  'central-wildcats': '/images/helmets/centralwildcats.png',
  'morton-hogs': '/images/helmets/mortonhogs.png',
  'leto-falcons-f11': '/images/helmets/leto.png',
  'waterbury-cowboys': '/images/helmets/waterbury.png',
  'lees-summit-tigers-f12': '/images/helmets/leesummit.png',
  'north-decatur-chargers': '/images/helmets/northdectur.png',
  'sacred-heart-hearts': '/images/helmets/sacredheart.png',
  'struthers-puledros-wildcats': '/images/helmets/struthers.png',
  'maury-commodores': '/images/helmets/maury.png',
  'union-redhawks': '/images/helmets/unionredhawks.png',
  'parkersburg-big-red': '/images/helmets/parkersburg.png',
  'mervo-mustangs': '/images/helmets/mervo.png',
  'pat-med-raiders': '/images/helmets/patmed.png',
  'huron-tigers': '/images/helmets/huron.png',
  'sandusky-redskins': '/images/helmets/sandusky.png',
};

export function helmetForTeam(teamId?: string | null) {
  return teamId ? helmetByTeamId[teamId] ?? null : null;
}

export { helmetByTeamId };
